# This is a basic workflow to help you get started with Actions

name: Provission Terraform.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions: write-all
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
defaults:
  run:
    shell: bash
    working-directory: "./staging/us-east-2"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tfplan:
    ## Only run TF Plan when a PR is opened
    if: github.event_name == 'pull_request'
    ## Only Run TF Plan when a PR is opened
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        #continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        #continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
            })

            // 2. Prepare format of the comment
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
  terraform-snyk-scan:
    if: github.event_name == 'pull_request'
    needs: tfplan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Scan Terraform Code for Security misconfigurations. Resolve All Critical and High before Merge to Main
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: "./staging/us-east-2"
          args: --severity-threshold=high

  tfapply:
    if: always() && github.event_name == 'push'
    needs: terraform-snyk-scan
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          id: init
          run: terraform init

        - name: Deploy Terraform
          run: terraform apply --auto-approve
  # this is to destroy all infrastroctur         
  tfdestroy:
    if: always() && github.event_name == 'workflow_dispatch'
    needs: tfapply
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          id: init
          run: terraform init

        - name: Destroy Terraform
          run: terraform destroy --auto-approve
    
