# This is a basic workflow to help you get started with Actions

name: Provission Terraform

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tfplan:
    ## Only Run TF Plan when a PR is opened
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        #continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-colo
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        #continue-on-error: true

      # # Runn a single command using the runners shell
      # - name: GHA Terraform
      #   run: echo "Welcome to my GHA Terraform Test"

      # # Runn a single command using the runners shell
      # - name: Display Date and Time
      #   run:  |
      #     date
      #     cat /etc/os-release

  tfapply:
    ## Only Run TF Plan when a PR is opened
    needs: build
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Deploy Terraform
          run: echo "Terraform Apply"

    